"""Canonical BestDish content — restaurants, chefs, dishes, buildings, farms.
Source of truth: the approved packaging artwork (Website Content Reference).
Allergen/label corrections from that doc are applied here (not the raw label errors).
"""

RESTAURANTS = {
    "la-palma": {
        "name": "La Palma",
        "address": "849 Dundas St W",
        "city": "Toronto, ON",
        "postal": "M6J 1V5",
        "blurb": "La Palma is known for its modern Italian cooking, combining traditional techniques with a focus on ingredient quality and precision.",
        "chef": "Craig Harding",
        "logo": "LaPalma.png",
    },
    "pukka": {
        "name": "Pukka",
        "address": "778 St Clair Ave W",
        "city": "Toronto, ON",
        "postal": "M6C 1B6",
        "blurb": "Pukka is known for its commitment to authentic Indian cooking, using fresh, locally sourced ingredients and traditional techniques to deliver bold, balanced flavours.",
        "chef": "Dinesh Butola",
        "logo": "Pukka.png",
    },
    "cheese-boutique": {
        "name": "Cheese Boutique",
        "address": "45 Ripley Ave",
        "city": "Toronto, ON",
        "postal": "M6S 3P2",
        "blurb": "Cheese Boutique is one of Canada's most respected specialty food retailers, known for sourcing and aging some of the finest cheeses in the country. Under the leadership of Afrim Pristine, it has become a destination for quality and expertise.",
        "chef": "Afrim Pristine",
        "logo": "CheeseBoutique.png",
    },
    "queen-and-beaver": {
        "name": "The Queen & Beaver",
        "address": "35 Elm St",
        "city": "Toronto, ON",
        "postal": "M5G 1H1",
        "blurb": "The Queen & Beaver is a refined gastropub known for classic dishes executed with precision and restraint.",
        "chef": "Duncan Simpson",
        "logo": "QueenBeaver.png",
    },
    "le-gourmand": {
        "name": "Le Gourmand",
        "address": "152 Spadina Ave",
        "city": "Toronto, ON",
        "postal": "M5V 3S6",
        "blurb": "Le Gourmand is known for its iconic cookies and long-standing reputation in Toronto.",
        "chef": "The Nunes Family",
        "logo": "LeGourmand.png",
    },
    "slowhand": {
        "name": "Slowhand",
        "address": "99 Pape Ave",
        "city": "Toronto, ON",
        "postal": "M4M 2V7",
        "blurb": "Slowhand is known for its sourdough-based pizza and its focus on fermentation and technique.",
        "chef": "Brett Feeley & Dan Ewing",
        "logo": "Slowhand.png",
    },
    "piano-piano": {
        "name": "Piano Piano",
        "address": "55 Colborne St",
        "city": "Toronto, ON",
        "postal": "M5E 1E3",
        "blurb": "Piano Piano is known for approachable Italian cooking with a focus on consistency and flavour.",
        "chef": "Victor Barry",
        "logo": "PianoPiano.png",
    },
    "death-in-venice": {
        "name": "Death in Venice",
        "address": "1418 Dundas St W",
        "city": "Toronto, ON",
        "postal": "M6J 1Y5",  # TODO: verify postal code
        "blurb": "Death in Venice Gelato Co. is a critically acclaimed, avant-garde gelateria in Toronto's Dundas West neighbourhood. Founded by Kaya Ogruce — a chemical engineer turned professional chef — the shop treats gelato making like a culinary experiment, famous for swapping traditional flavours for complex, gastronomic combinations that balance sweet and savoury profiles.",
        "chef": "Kaya Ogruce",
        "logo": "DeathInVenice.png",
    },
}

# Map coordinates (geocoded from the verified addresses) + neighbourhood.
# Carbon Snack Bar shares Carbon Bar's address; its pin is nudged so both show.
_RESTAURANT_GEO = {
    "la-palma":         {"lat": 43.651347, "lng": -79.410118, "hood": "Trinity Bellwoods"},
    "pukka":            {"lat": 43.681135, "lng": -79.429227, "hood": "Wychwood"},
    "cheese-boutique":  {"lat": 43.638540, "lng": -79.475088, "hood": "Swansea"},
    "queen-and-beaver": {"lat": 43.657345, "lng": -79.383358, "hood": "Yonge & Dundas"},
    "le-gourmand":      {"lat": 43.648251, "lng": -79.396455, "hood": "Fashion District"},
    "slowhand":         {"lat": 43.661785, "lng": -79.337644, "hood": "Leslieville"},
    "piano-piano":      {"lat": 43.649041, "lng": -79.374650, "hood": "St. Lawrence"},
    "death-in-venice":  {"lat": 43.649650, "lng": -79.426750, "hood": "Little Portugal"},
}
for _slug, _geo in _RESTAURANT_GEO.items():
    RESTAURANTS[_slug].update(_geo)

DISHES = [
    {
        "slug": "cheesemaster-mac",
        "name": "Cheese Master Mac",
        "category": "Savoury",
        "restaurant": "cheese-boutique",
        "tagline": "Creamy, indulgent mac & cheese made with artisanal cheeses. Rich, comforting, and perfectly cheesy.",
        "chef_note": "It is no secret that I adore my mother's cooking, and she has taught me all of her recipes. The inspiration for this dish comes from a simple, yet resourceful place — turning her beloved baked pasta into this version was a natural evolution.",
        "chef_signature": "Afrim Pristine",
        "image": "cheesemaster-mac.jpg",
        "weight": "535 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Cheddar cheese, Milk, Cavatelli pasta (flour, water), Gruyère cheese, Cream, Parmigiano Reggiano cheese, White bread (flour, water, butter, sugar, salt, yeast), Butter, Extra virgin olive oil, Flour, Granulated garlic, Onion powder, Spices.",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "780",
            "Fat": "51 g (68% DV)",
            "Saturated": "30 g + Trans 1.5 g (158% DV)",
            "Carbohydrate": "54 g",
            "Fibre": "2 g (7% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "36 g",
            "Cholesterol": "150 mg",
            "Sodium": "960 mg (42% DV)",
            "Calcium": "1000 mg (78% DV)",
            "Potassium": "350 mg (11% DV)",
            "Iron": "1.75 mg (10% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Bake 25–30 minutes until bubbly and golden on top. Remove foil and heat an additional 5 minutes. Let rest 2 minutes before serving."),
            ("Microwave", "Remove lid. Heat on high 4–5 minutes, stirring halfway. Let rest 2 minutes before serving."),
        ],
    },
    {
        "slug": "100-layer-lasagna",
        "name": "100 Layer Lasagna",
        "category": "Savoury",
        "restaurant": "la-palma",
        "tagline": "A fully handmade lasagna built layer by layer using pasta, slow-cooked meat, and béchamel. Each layer is intentional, creating a structure and texture that defines the dish.",
        "chef_note": "This dish represents the way we build food in the restaurant — with patience, repetition, and attention to detail. Every layer matters.",
        "chef_signature": "Craig Harding",
        "image": "100layer.jpg",
        "hero_image": "100layer-wide.jpg",
        "weight": "503 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Canned tomatoes, Mozzarella cheese, Flour, Ground meat mix (beef, pork, veal), Whole milk, Pasteurized egg yolks, Grana Padano cheese, Chicken stock, Olive oil, Onions, White wine, Butter, Carrots, Tomato paste, Whole eggs, Celery, Garlic.",
        "contains": "Wheat, Milk, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "570",
            "Fat": "32 g (42% DV)",
            "Saturated": "14 g + Trans 0.5 g (73% DV)",
            "Carbohydrate": "42 g",
            "Fibre": "4 g (13% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "30 g",
            "Cholesterol": "165 mg",
            "Sodium": "750 mg (33% DV)",
            "Calcium": "450 mg (35% DV)",
            "Potassium": "650 mg (19% DV)",
            "Iron": "3.5 mg (20% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Bake 30–35 minutes. Remove foil. Let rest 2 minutes before serving."),
            ("Microwave", "Remove lid. Heat on high 5–7 minutes. Let rest 2 minutes before serving."),
        ],
    },
    {
        "slug": "cheeseburger-pot-pie",
        "name": "Cheese Burger Pot Pie",
        "category": "Savoury",
        "restaurant": "queen-and-beaver",
        "tagline": "This dish takes the core elements of a cheeseburger and rebuilds them inside a pastry shell, creating a structured, balanced version of a familiar comfort food.",
        "chef_note": "Comfort food works best when it's built properly. This is about balance, not excess.",
        "chef_signature": "Duncan Simpson",
        "image": "cheeseburger-pot-pie.jpg",
        "weight": "290 g",
        "serving": "1 serving (300 g)",
        "ingredients": "Flour, Ground beef, Cheddar cheese, Beef fat, Shortening, Pickles, Onion, Beef stock, Water, Worcestershire sauce (vinegar, water, molasses, sugar, salt, anchovies, tamarind extract, onions, garlic, spice, natural and artificial flavours), Mustard, White wine vinegar, Egg yolk, Tomato paste, Salt, Garlic, Sesame seeds, Black pepper.",
        "contains": "Wheat, Milk, Fish, Mustard, Egg, Sesame, Sulphites.",
        "may_contain": "Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "900",
            "Fat": "50 g (67% DV)",
            "Saturated": "17 g + Trans 1 g (90% DV)",
            "Carbohydrate": "70 g",
            "Fibre": "3 g (11% DV)",
            "Sugars": "2 g (2% DV)",
            "Protein": "41 g",
            "Cholesterol": "120 mg",
            "Sodium": "780 mg (34% DV)",
            "Calcium": "350 mg (25% DV)",
            "Potassium": "450 mg (14% DV)",
            "Iron": "6.5 mg (35% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid. Bake 25–30 minutes. Let rest 2 minutes before serving."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "butter-chicken",
        "name": "Butter Chicken Curry",
        "category": "Savoury",
        "restaurant": "pukka",
        "tagline": "A classic North Indian dish built on a slow-cooked tomato base, finished with cream and a balanced blend of spices. Designed to hold depth and structure through reheating.",
        "chef_note": "At Pukka, we believe in real food — thoughtfully prepared, properly cooked, and rooted in tradition. This dish reflects that approach.",
        "chef_signature": "Dinesh Butola",
        "image": "butter-chicken.jpg",
        "weight": "435 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Basmati rice, Chicken breast, Canned tomato purée, Diced onions, Cream, Canned tomato paste, Plain yogurt (milk, bacteria culture), Butter, Vegetable oil, Garlic, Salt, Lemon juice, Fresh ginger, Sugar, Garam masala, Spices.",
        "contains": "Milk.",
        "may_contain": "Wheat, Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "410",
            "Fat": "23 g (31% DV)",
            "Saturated": "10 g + Trans 0.2 g (50% DV)",
            "Carbohydrate": "14 g",
            "Fibre": "2 g (9% DV)",
            "Sugars": "9 g (9% DV)",
            "Protein": "36 g",
            "Cholesterol": "115 mg",
            "Sodium": "870 mg (38% DV)",
            "Calcium": "75 mg (6% DV)",
            "Potassium": "800 mg (23% DV)",
            "Iron": "2.5 mg (13% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Bake 20–25 minutes. Remove foil. Let rest 2 minutes before serving."),
            ("Microwave", "Remove lid. Heat on high 4–6 minutes, stirring halfway. Let rest 2 minutes before serving."),
        ],
    },
    {
        "slug": "le-grand-fromage",
        "name": "Le Grand Fromage Pizza",
        "category": "Savoury",
        "restaurant": "slowhand",
        "tagline": "A Detroit-style pizza with a thick base, crisp edges, and a soft interior, designed to maintain structure and texture after reheating.",
        "chef_note": "Slowhand Pizza was born from an obsession with Detroit-style pizza, sourdough fermentation, and the pursuit of the perfect crispy edge.",
        "chef_signature": "Brett Feeley & Dan Ewing",
        "image": "le-grand-fromage.jpg",
        "weight": "475 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Pizza dough (flour, water), Mozzarella cheese, Pizza sauce (tomatoes, salt, citric acid), Pecorino cheese (sheep milk, salt, lamb rennet, cheese cultures).",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "800",
            "Fat": "32 g (42% DV)",
            "Saturated": "13 g + Trans 0.5 g (65% DV)",
            "Carbohydrate": "90 g",
            "Fibre": "5 g (17% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "36 g",
            "Cholesterol": "70 mg",
            "Sodium": "1560 mg (68% DV)",
            "Calcium": "550 mg (43% DV)",
            "Potassium": "400 mg (12% DV)",
            "Iron": "6.5 mg (35% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 425°F. Place directly on the middle rack. Bake 10–12 minutes until cheese is bubbly. Let rest 2 minutes before serving."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "nutella-tiramisu",
        "name": "Nutella Tiramisu",
        "category": "Sweet",
        "restaurant": "piano-piano",
        "tagline": "A variation on tiramisu using Nutella cream and mascarpone mousse, layered with espresso-soaked sponge.",
        "chef_note": "This is a playful version of a classic, built to be rich but balanced.",
        "chef_signature": "Victor Barry",
        "image": "nutella-tiramisu-dish.jpg",
        "weight": "290 g",
        "serving": "1 serving (55 g)",
        "ingredients": "Water, Mascarpone (milk and cream, skim milk powder, fructose, citric acid, salt, potassium sorbate, tapioca starch, calcium chloride, natural flavour, guar gum, monoglyceride, xanthan gum), Egg white, Sugar, Egg yolk, Instant espresso coffee, Nutella (sugar, modified palm oil, hazelnuts, skim milk powder, cocoa, soy lecithin, vanillin), Cream, Gelatin.",
        "contains": "Milk, Egg, Hazelnut, Soybean.",
        "may_contain": "Wheat, Anchovies, Mustard, Sesame and Pecan.",
        "nutrition": {
            "Calories": "140",
            "Fat": "9 g (12% DV)",
            "Saturated": "5 g + Trans 0.2 g (26% DV)",
            "Carbohydrate": "11 g",
            "Fibre": "0 g (0% DV)",
            "Sugars": "8 g (8% DV)",
            "Protein": "2 g",
            "Cholesterol": "60 mg",
            "Sodium": "30 mg (1% DV)",
            "Calcium": "30 mg (3% DV)",
            "Potassium": "40 mg (1% DV)",
            "Iron": "0.2 mg (2% DV)",
        },
        "heat": [
            ("Serve", "Do not cook. Remove from the freezer and let sit at room temperature for 10 minutes."),
        ],
    },
    {
        "slug": "chocolate-chip-cookies",
        "name": "The Best Chocolate Chip Cookie",
        "category": "Sweet",
        "restaurant": "le-gourmand",
        "tagline": "A raw cookie designed to be baked fresh, delivering a soft centre and crisp edges.",
        "chef_note": "This is the cookie we built our name on.",
        "chef_signature": "The Nunes Family",
        "image": "chocolate-chip-cookies-dish.jpg",
        "weight": "130 g (4 cookies)",
        "serving": "1 cookie (30 g)",
        "ingredients": "Flour, Butter, Sugars (brown sugar, white sugar), Chocolate chips (sugar, chocolate, cocoa butter, milk ingredients, soy lecithin, natural flavour), Egg, Vanilla extract, Salt, Baking soda.",
        "contains": "Wheat, Milk, Soybean, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "140",
            "Fat": "7 g (9% DV)",
            "Saturated": "3 g + Trans 0.2 g (16% DV)",
            "Carbohydrate": "17 g",
            "Fibre": "1 g (2% DV)",
            "Sugars": "10 g (10% DV)",
            "Protein": "2 g",
            "Cholesterol": "20 mg",
            "Sodium": "90 mg (4% DV)",
            "Calcium": "10 mg (1% DV)",
            "Potassium": "40 mg (1% DV)",
            "Iron": "0.5 mg (3% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 350°F. Remove from all packaging and place the frozen cookies on a baking sheet. Bake 12–14 minutes. Let rest 2 minutes before serving."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "gelato",
        "name": "Gelato",
        "category": "Sweet",
        "restaurant": "death-in-venice",
        "tagline": "Small-batch Toronto gelato, churned by hand in bold, unexpected flavours.",
        "chef_bio": "Ogruce originally trained as a chef and worked in Michelin-starred restaurants globally before transitioning into artisanal gelato. After a motorcycle trip through Sicily, he and his business partner Maddalena Fuller founded Death in Venice in 2015.",
        "chef_signature": "Kaya Ogruce",
        "image": "gelato.jpg",
        "heat": [
            ("Serve", "Keep frozen. Let sit at room temperature for a few minutes before scooping."),
        ],
    },
]

FARMS = [
    {
        "slug": "100km-foods",
        "name": "100km Foods",
        "blurb": "Founded in 2008 by Paul Sawtell and Grace Mandarano. Distributes from Ontario farms to chefs who care where ingredients come from.",
        "people": "Paul Sawtell & Grace Mandarano",
        "region": "Ontario",
        "supplies": "Meat, dairy, produce, grains.",
        "logo": "100kmfoods.png",
    },
    {
        "slug": "the-new-farm",
        "name": "The New Farm",
        "blurb": "Certified organic. Family-run. Cycle-driven. The farm that anchors Toronto's best kitchens through every season.",
        "people": "Brent Preston & Gillian Flies",
        "region": "Creemore, ON",
        "supplies": "Salad greens, vegetables, herbs.",
        "logo": "thenewfarm.png",
    },
]

BUILDINGS = [
    {"slug": "east-room",      "name": "East Room",      "address": "507 King St E, Toronto",                  "type": "Co-working",          "status": "Live",        "lat": 43.65540, "lng": -79.35900},
    {"slug": "the-selby",      "name": "The Selby",      "address": "592 Sherbourne St, Toronto",              "type": "Luxury rental",       "status": "Live",        "lat": 43.66900, "lng": -79.37620},
    {"slug": "club-apex",      "name": "Club Apex",      "address": "Yonge & Bloor (3rd floor)",               "type": "Members club",        "status": "Live",        "lat": 43.67100, "lng": -79.38680},
    {"slug": "maple-house",    "name": "Maple House",    "address": "Canary Landing, Front St E & Cherry St",  "type": "Luxury rental",       "status": "Live",        "lat": 43.65280, "lng": -79.35480},
    {"slug": "king-charlotte", "name": "King Charlotte", "address": "11 Charlotte St, Toronto",                "type": "Condominium",         "status": "Q3 2026",     "lat": 43.64650, "lng": -79.39390},
    {"slug": "the-well",       "name": "The Well",       "address": "486 Front St W, Toronto",                 "type": "Mixed-use residence", "status": "Q4 2026",     "lat": 43.64200, "lng": -79.39990},
    {"slug": "one-bloor-east", "name": "One Bloor East", "address": "1 Bloor St E, Toronto",                   "type": "Luxury rental",       "status": "Q4 2026",     "lat": 43.67020, "lng": -79.38550},
    {"slug": "sloane",         "name": "Sloane",         "address": "5 York Garden Way, North York",           "type": "Rental community",    "status": "August 2026", "lat": 43.72500, "lng": -79.45450},
]

NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
]

FOOTER_NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
    ("Buildings",     "/buildings.html"),
    ("For properties","/for-properties.html"),
    ("For restaurants","/for-restaurants.html"),
    ("FAQ",           "/faq.html"),
]
