"""Canonical BestDish content — restaurants, chefs, dishes, buildings, farms.
Source of truth: the approved packaging artwork (Website Content Reference).
Allergen/label corrections from that doc are applied here (not the raw label errors).
"""

RESTAURANTS = {
    "la-palma": {
        "name": "La Palma",
        "address": "849 Dundas St W",
        "city": "Toronto, ON",
        "postal": "M6J 1V5",
        "blurb": "La Palma is known for its modern Italian cooking, combining traditional techniques with a focus on ingredient quality and precision.",
        "chef": "Craig Harding",
        "logo": "LaPalma.png",
    },
    "lucie": {
        "name": "Lucie",
        "address": "100 Yonge St",
        "city": "Toronto, ON",
        "postal": "M5C 2W1",
        "blurb": "Nestled in the mountains of southwestern France near the Spanish border, Lucie filled her home with the aromas of butter, roasting meat, and simmering wine, cooking each meal with care for her grandson. Restaurant Lucie is an homage to those afternoons — and to her belief that one of the greatest acts of love is feeding people well.",
        "chef": "Michael Angeloni",
        "logo": "Lucie.png",
    },
    "pukka": {
        "name": "Pukka",
        "address": "778 St Clair Ave W",
        "city": "Toronto, ON",
        "postal": "M6C 1B6",
        "blurb": "Pukka is known for its commitment to authentic Indian cooking, using fresh, locally sourced ingredients and traditional techniques to deliver bold, balanced flavours.",
        "chef": "Dinesh Butola",
        "logo": "Pukka.png",
    },
    "carbon-bar": {
        "name": "The Carbon Bar",
        "address": "99 Queen St E",
        "city": "Toronto, ON",
        "postal": "M5C 1S1",
        "blurb": "First opened in 2013, The Carbon Bar is an elevated downtown Toronto dining room known for live-fire, Texas-style BBQ, steaks, and seafood — all delivered with serious hospitality.",
        "chef": "Taylor Wells",
        "logo": "CarbonBar.png",
    },
    "carbon-snack-bar": {
        "name": "Carbon Snack Bar",
        "address": "99 Queen St E",
        "city": "Toronto, ON",
        "postal": "M5C 1S1",
        "blurb": "The Carbon Snack Bar is the all-day King West counterpart to Toronto's acclaimed Carbon Bar — a bright, fast-casual spot for coffee, sandwiches, salads, and house-made snacks and sweets, backed by the same kitchen pedigree.",
        "chef": "Taylor Wells",
        "logo": "CarbonBar.png",
    },
    "cheese-boutique": {
        "name": "Cheese Boutique",
        "address": "45 Ripley Ave",
        "city": "Toronto, ON",
        "postal": "M6S 3P2",
        "blurb": "Cheese Boutique is one of Canada's most respected specialty food retailers, known for sourcing and aging some of the finest cheeses in the country. Under the leadership of Afrim Pristine, it has become a destination for quality and expertise.",
        "chef": "Afrim Pristine",
        "logo": "CheeseBoutique.png",
    },
    "queen-and-beaver": {
        "name": "The Queen & Beaver",
        "address": "35 Elm St",
        "city": "Toronto, ON",
        "postal": "M5G 1H1",
        "blurb": "The Queen & Beaver is a downtown Toronto gastropub now in its 18th year, specializing in proper British classics made from scratch — Welsh Rarebit, Scotch Eggs, Fish & Chips, and Pies.",
        "chef": "Duncan Simpson",
        "logo": "QueenBeaver.png",
    },
    "le-gourmand": {
        "name": "Le Gourmand",
        "address": "152 Spadina Ave",
        "city": "Toronto, ON",
        "postal": "M5V 3S6",
        "blurb": "Le Gourmand is known for its iconic cookies and long-standing reputation in Toronto.",
        "chef": "The Nunes Family",
        "logo": "LeGourmand.png",
    },
    "slowhand": {
        "name": "Slowhand",
        "address": "99 Pape Ave",
        "city": "Toronto, ON",
        "postal": "M4M 2V7",
        "blurb": "Slowhand is known for its sourdough-based pizza and its focus on fermentation and technique.",
        "chef": "Brett Feeley & Dan Ewing",
        "logo": "Slowhand.png",
    },
    "piano-piano": {
        "name": "Piano Piano",
        "address": "55 Colborne St",
        "city": "Toronto, ON",
        "postal": "M5E 1E3",
        "blurb": "Piano Piano is known for approachable Italian cooking with a focus on consistency and flavour.",
        "chef": "Victor Barry",
        "logo": "PianoPiano.png",
    },
    "forno-cultura": {
        "name": "Forno Cultura",
        "address": "609 King St W",
        "city": "Toronto, ON",
        "postal": "M5V 1M5",
        "blurb": "An artisanal Italian bakery — sourdough, pastry, biscotti made with patience and respect for tradition.",
        "chef": "Andrea Mastrandrea",
        "logo": "FornoCultura.png",
    },
}

# Map coordinates (geocoded from the verified addresses) + neighbourhood.
# Carbon Snack Bar shares Carbon Bar's address; its pin is nudged so both show.
_RESTAURANT_GEO = {
    "la-palma":         {"lat": 43.651347, "lng": -79.410118, "hood": "Trinity Bellwoods"},
    "lucie":            {"lat": 43.649704, "lng": -79.378530, "hood": "Financial District"},
    "pukka":            {"lat": 43.681135, "lng": -79.429227, "hood": "Wychwood"},
    "carbon-bar":       {"lat": 43.653271, "lng": -79.374863, "hood": "Moss Park"},
    "carbon-snack-bar": {"lat": 43.653271, "lng": -79.373800, "hood": "Moss Park"},
    "cheese-boutique":  {"lat": 43.638540, "lng": -79.475088, "hood": "Swansea"},
    "queen-and-beaver": {"lat": 43.657345, "lng": -79.383358, "hood": "Yonge & Dundas"},
    "le-gourmand":      {"lat": 43.648251, "lng": -79.396455, "hood": "Fashion District"},
    "slowhand":         {"lat": 43.661785, "lng": -79.337644, "hood": "Leslieville"},
    "piano-piano":      {"lat": 43.649041, "lng": -79.374650, "hood": "St. Lawrence"},
    "forno-cultura":    {"lat": 43.644225, "lng": -79.400595, "hood": "King West"},
}
for _slug, _geo in _RESTAURANT_GEO.items():
    RESTAURANTS[_slug].update(_geo)

DISHES = [
    {
        "slug": "cheesemaster-mac",
        "name": "Cheese Master Mac",
        "category": "Savoury",
        "restaurant": "cheese-boutique",
        "tagline": "Built from a family recipe using aged Ontario cheddar and a rich, creamy sauce.",
        "chef_note": "It is no secret that I adore my mother's cooking, and she has taught me all of her recipes. The inspiration for this dish comes from a simple, yet resourceful place — turning her beloved baked pasta into this version was a natural evolution.",
        "chef_signature": "Afrim Pristine",
        "image": "cheesemaster-mac.jpg",
        "weight": "300 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Cheddar cheese, Milk, Cavatelli pasta (flour, water), Gruyère cheese, Cream, Parmigiano Reggiano cheese, White bread (flour, water, butter, sugar, salt, yeast), Butter, Extra virgin olive oil, Flour, Granulated garlic, Onion powder, Spices.",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "780",
            "Fat": "51 g (68% DV)",
            "Saturated": "30 g + Trans 1.5 g (158% DV)",
            "Carbohydrate": "54 g",
            "Fibre": "2 g (7% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "36 g",
            "Cholesterol": "150 mg",
            "Sodium": "960 mg (42% DV)",
            "Calcium": "1000 mg (78% DV)",
            "Potassium": "350 mg (11% DV)",
            "Iron": "1.75 mg (10% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Heat 25–30 minutes. Remove foil and heat an additional 5 minutes."),
            ("Microwave", "Remove lid. Heat on high 4–5 minutes, stirring halfway."),
        ],
    },
    {
        "slug": "100-layer-lasagna",
        "name": "100 Layer Lasagna",
        "category": "Savoury",
        "restaurant": "la-palma",
        "tagline": "Handmade. One hundred layers. Built with locally sourced meats and Italian cheeses.",
        "chef_note": "This dish represents the way we build food in the restaurant — with patience, repetition, and attention to detail. Every layer matters.",
        "chef_signature": "Craig Harding",
        "image": "100layer.jpg",
        "weight": "300 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Canned tomatoes, Mozzarella cheese, Flour, Ground meat mix (beef, pork, veal), Whole milk, Pasteurized egg yolks, Grana Padano cheese, Chicken stock, Olive oil, Onions, White wine, Butter, Carrots, Tomato paste, Whole eggs, Celery, Garlic.",
        "contains": "Wheat, Milk, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "570",
            "Fat": "32 g (42% DV)",
            "Saturated": "14 g + Trans 0.5 g (73% DV)",
            "Carbohydrate": "42 g",
            "Fibre": "4 g (13% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "30 g",
            "Cholesterol": "165 mg",
            "Sodium": "750 mg (33% DV)",
            "Calcium": "450 mg (35% DV)",
            "Potassium": "650 mg (19% DV)",
            "Iron": "3.5 mg (20% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Heat 30–35 minutes. Remove foil and heat an additional 5 minutes."),
            ("Microwave", "Remove lid. Heat on high 5–7 minutes."),
        ],
    },
    {
        "slug": "cheeseburger-pot-pie",
        "name": "Cheeseburger Pot Pie",
        "category": "Savoury",
        "restaurant": "queen-and-beaver",
        "tagline": "A proper pie built from a cheeseburger, wrapped in pastry.",
        "chef_note": "Comfort food works best when it's built properly. This is about balance, not excess.",
        "chef_signature": "Duncan Simpson",
        "image": "cheeseburger-pot-pie.jpg",
        "weight": "600 g (2 servings)",
        "serving": "1 serving (300 g)",
        "ingredients": "Flour, Ground beef, Cheddar cheese, Beef fat, Shortening, Pickles, Onion, Beef stock, Water, Worcestershire sauce (vinegar, water, molasses, sugar, salt, anchovies, tamarind extract, onions, garlic, spice, natural and artificial flavours), Mustard, White wine vinegar, Egg yolk, Tomato paste, Salt, Garlic, Sesame seeds, Black pepper.",
        "contains": "Wheat, Milk, Fish, Mustard, Egg, Sesame, Sulphites.",
        "may_contain": "Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "900",
            "Fat": "50 g (67% DV)",
            "Saturated": "17 g + Trans 1 g (90% DV)",
            "Carbohydrate": "70 g",
            "Fibre": "3 g (11% DV)",
            "Sugars": "2 g (2% DV)",
            "Protein": "41 g",
            "Cholesterol": "120 mg",
            "Sodium": "780 mg (34% DV)",
            "Calcium": "350 mg (25% DV)",
            "Potassium": "450 mg (14% DV)",
            "Iron": "6.5 mg (35% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Heat 25–30 minutes. Remove foil and heat an additional 5 minutes."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "butter-chicken",
        "name": "Butter Chicken",
        "category": "Savoury",
        "restaurant": "pukka",
        "tagline": "A traditional butter chicken curry made with tomato, cream, and warm spices.",
        "chef_note": "At Pukka, we believe in real food — thoughtfully prepared, properly cooked, and rooted in tradition. This dish reflects that approach.",
        "chef_signature": "Dinesh Butola",
        "image": "butter-chicken.jpg",
        "weight": "300 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Basmati rice, Chicken breast, Tomato purée, Diced onions, Cream, Tomato paste, Plain yogurt (milk, bacteria culture), Butter, Vegetable oil, Garlic, Salt, Lemon juice, Fresh ginger, Sugar, Garam masala, Spices.",
        "contains": "Milk.",
        "may_contain": "Wheat, Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "410",
            "Fat": "23 g (31% DV)",
            "Saturated": "10 g + Trans 0.2 g (50% DV)",
            "Carbohydrate": "14 g",
            "Fibre": "2 g (9% DV)",
            "Sugars": "9 g (9% DV)",
            "Protein": "36 g",
            "Cholesterol": "115 mg",
            "Sodium": "870 mg (38% DV)",
            "Calcium": "75 mg (6% DV)",
            "Potassium": "800 mg (23% DV)",
            "Iron": "2.5 mg (13% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 375°F. Remove lid and cover with foil. Heat 20–25 minutes."),
            ("Microwave", "Remove lid. Heat on high 4–6 minutes, stirring halfway."),
        ],
    },
    {
        "slug": "beef-bourguignon",
        "name": "Beef Bourguignon",
        "category": "Savoury",
        "restaurant": "lucie",
        "tagline": "Smoked beef and bacon, braised slowly in red wine with potatoes, mushrooms, and carrots.",
        "chef_note": "Beef Bourguignon is a dish that reminds me why I love cooking — simple ingredients transformed through patience, care, and time.",
        "chef_signature": "Michael Angeloni",
        "image": "beef-bourguignon-dish.jpg",
        "weight": "300 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Potatoes, Smoked beef brisket (beef, salt, pepper, canola oil), Beef stock, Mushrooms, Onions, Red wine, Smoked bacon (pork, brown sugar, white sugar, salt, sodium nitrate), Carrots, Cream, Butter, Tomato paste, Garlic, Spices, Salt.",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "350",
            "Fat": "20 g (27% DV)",
            "Saturated": "8 g + Trans 0.5 g (45% DV)",
            "Carbohydrate": "27 g",
            "Fibre": "3 g (12% DV)",
            "Sugars": "4 g (4% DV)",
            "Protein": "17 g",
            "Cholesterol": "70 mg",
            "Sodium": "660 mg (29% DV)",
            "Calcium": "50 mg (4% DV)",
            "Potassium": "750 mg (22% DV)",
            "Iron": "2.5 mg (13% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 350°F. Remove lid; cover with foil. Heat 25–30 minutes. Uncover and heat 5 more minutes to thicken the sauce. Rest 2 minutes before serving."),
            ("Microwave", "Remove lid. Heat on high 5–7 minutes, stirring halfway. Rest 2 minutes before serving."),
        ],
    },
    {
        "slug": "pitmaster-platter",
        "name": "Pitmaster Platter",
        "category": "Savoury",
        "restaurant": "carbon-bar",
        "tagline": "Signature smokehouse platter featuring St. Louis ribs, smoked brisket, cheddar jalapeño sausage, and pulled pork.",
        "chef_note": "Our Pitmaster Platter is built to showcase the best of Texas-style barbecue — slow-smoked meats, classic sides, and the kind of feast meant to be shared.",
        "chef_signature": "Taylor Wells",
        "image": "pitmaster-platter.jpg",
        "weight": "1050 g (2 servings)",
        "serving": "1 serving (525 g)",
        "ingredients": "Brisket (beef, salt, pepper, canola oil), St. Louis style ribs (pork, kosher salt, black pepper, smoked paprika, chili flakes, granulated onion, granulated garlic), Pulled pork (pork, rosemary, fennel seed, chili flakes, brown sugar, canola oil, granulated onion, granulated garlic, kosher salt), Cheddar & jalapeño sausage (ground pork, garlic powder, onion powder, salt, pepper, paprika, chili flakes, pickled jalapeño, fresh jalapeño, apple cider vinegar, Mexican oregano, white cheddar cheese).",
        "contains": "Milk.",
        "may_contain": "Wheat, Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "880",
            "Fat": "55 g (73% DV)",
            "Saturated": "19 g + Trans 0 g (95% DV)",
            "Carbohydrate": "28 g",
            "Fibre": "1.5 g (5% DV)",
            "Sugars": "18 g (18% DV)",
            "Protein": "70 g",
            "Cholesterol": "245 mg",
            "Sodium": "1850 mg (80% DV)",
            "Vitamin D": "1.2 mcg (6% DV)",
            "Calcium": "210 mg (16% DV)",
            "Iron": "5.0 mg (28% DV)",
            "Potassium": "1150 mg (34% DV)",
        },
        "heat": [
            ("Sous-vide", "Bring a large pot ¾ full of water to a simmer. Place the sealed bags in the water for 6 minutes. Remove with tongs, open carefully, and slice the sausage into pieces."),
            ("Oven", "Preheat to 375°F and line a baking sheet with parchment. Remove the meats from all packaging and arrange on the sheet (layer the brisket). Bake on the lower rack 8–10 minutes."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "le-grand-fromage",
        "name": "Le Grand Fromage",
        "category": "Savoury",
        "restaurant": "slowhand",
        "tagline": "Toronto's famous sourdough deep-dish pizza. Made Detroit style with the signature E.P.I.C. (every piece is a corner) crust.",
        "chef_note": "Slowhand Pizza was born from an obsession with Detroit-style pizza, sourdough fermentation, and the pursuit of the perfect crispy edge.",
        "chef_signature": "Brett Feeley & Dan Ewing",
        "image": "le-grand-fromage.jpg",
        "weight": "300 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Pizza dough (flour, water), Mozzarella cheese, Pizza sauce (tomatoes, salt, citric acid), Pecorino cheese (sheep milk, salt, lamb rennet, cheese cultures).",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "800",
            "Fat": "32 g (42% DV)",
            "Saturated": "13 g + Trans 0.5 g (65% DV)",
            "Carbohydrate": "90 g",
            "Fibre": "5 g (17% DV)",
            "Sugars": "7 g (7% DV)",
            "Protein": "36 g",
            "Cholesterol": "70 mg",
            "Sodium": "1560 mg (68% DV)",
            "Calcium": "550 mg (43% DV)",
            "Potassium": "400 mg (12% DV)",
            "Iron": "6.5 mg (35% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 425°F. Remove from the box and place on a baking tray. Heat 10–12 minutes."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "butter-tarts",
        "name": "Butter Tarts",
        "category": "Sweet",
        "restaurant": "carbon-snack-bar",
        "tagline": "Four traditional Canadian desserts with a sweet filling and flaky crust.",
        "chef_note": "At The Carbon Snack Bar, we make our butter tarts the old-fashioned way — rich, buttery, and unapologetically indulgent. With a flaky pastry shell and a perfectly gooey centre, they're a nostalgic Canadian classic done right.",
        "chef_signature": "Taylor Wells",
        "image": "butter-tarts.webp",
        "weight": "220 g (4 tarts)",
        "serving": "1 tart (55 g)",
        "ingredients": "Sugars (brown sugar, corn syrup, maple syrup), Butter, Flour, Liquid eggs, Water, Apple cider vinegar, Salt, Vanilla extract.",
        "contains": "Wheat, Milk, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "220",
            "Fat": "11 g (15% DV)",
            "Saturated": "5 g + Trans 0.2 g (26% DV)",
            "Carbohydrate": "27 g",
            "Fibre": "0 g (0% DV)",
            "Sugars": "15 g (15% DV)",
            "Protein": "2 g",
            "Cholesterol": "50 mg",
            "Sodium": "180 mg (8% DV)",
            "Calcium": "20 mg (2% DV)",
            "Potassium": "50 mg (1% DV)",
            "Iron": "0.75 mg (4% DV)",
        },
        "heat": [
            ("Defrost", "Remove from the freezer and let sit at room temperature for 10 minutes."),
            ("Microwave", "Not recommended."),
        ],
    },
    {
        "slug": "nutella-tiramisu",
        "name": "Nutella Tiramisu",
        "category": "Sweet",
        "restaurant": "piano-piano",
        "tagline": "Layered mascarpone and Nutella cream with espresso.",
        "chef_note": "This is a playful version of a classic, built to be rich but balanced.",
        "chef_signature": "Victor Barry",
        "image": "nutella-tiramisu-dish.jpg",
        "weight": "55 g",
        "serving": "1 serving (55 g)",
        "ingredients": "Water, Mascarpone (milk and cream, skim milk powder, fructose, citric acid, salt, potassium sorbate, tapioca starch, calcium chloride, natural flavour, guar gum, monoglyceride, xanthan gum), Egg white, Sugar, Egg yolk, Instant espresso coffee, Nutella (sugar, modified palm oil, hazelnuts, skim milk powder, cocoa, soy lecithin, vanillin), Cream, Gelatin.",
        "contains": "Milk, Egg, Hazelnut, Soybean.",
        "may_contain": "Wheat, Anchovies, Mustard, Sesame and Pecan.",
        "nutrition": {
            "Calories": "140",
            "Fat": "9 g (12% DV)",
            "Saturated": "5 g + Trans 0.2 g (26% DV)",
            "Carbohydrate": "11 g",
            "Fibre": "0 g (0% DV)",
            "Sugars": "8 g (8% DV)",
            "Protein": "2 g",
            "Cholesterol": "60 mg",
            "Sodium": "30 mg (1% DV)",
            "Calcium": "30 mg (3% DV)",
            "Potassium": "40 mg (1% DV)",
            "Iron": "0.2 mg (2% DV)",
        },
        "heat": [
            ("Serve", "Keep frozen, or thaw before serving. Do not heat."),
        ],
    },
    {
        "slug": "chocolate-chip-cookies",
        "name": "Chocolate Chip Cookies",
        "category": "Sweet",
        "restaurant": "le-gourmand",
        "tagline": "Four raw cookies designed to be baked fresh, delivering a soft centre and crisp edges.",
        "chef_note": "This is the cookie we built our name on.",
        "chef_signature": "The Nunes Family",
        "image": "chocolate-chip-cookies-dish.jpg",
        "weight": "120 g (4 cookies)",
        "serving": "1 cookie (30 g)",
        "ingredients": "Flour, Butter, Sugars (brown sugar, white sugar), Chocolate chips (sugar, chocolate, cocoa butter, milk ingredients, soy lecithin, natural flavour), Egg, Vanilla extract, Salt, Baking soda.",
        "contains": "Wheat, Milk, Soybean, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "140",
            "Fat": "7 g (9% DV)",
            "Saturated": "3 g + Trans 0.2 g (16% DV)",
            "Carbohydrate": "17 g",
            "Fibre": "1 g (2% DV)",
            "Sugars": "10 g (10% DV)",
            "Protein": "2 g",
            "Cholesterol": "20 mg",
            "Sodium": "90 mg (4% DV)",
            "Calcium": "10 mg (1% DV)",
            "Potassium": "40 mg (1% DV)",
            "Iron": "0.5 mg (3% DV)",
        },
        "heat": [
            ("Oven", "Preheat to 360°F. Remove from all packaging and place the frozen cookies on a baking sheet. Bake 12 minutes. Let rest 2 minutes before serving."),
            ("Microwave", "Not recommended."),
        ],
    },
]

FARMS = [
    {
        "slug": "100km-foods",
        "name": "100km Foods",
        "blurb": "Founded in 2008 by Paul Sawtell and Grace Mandarano. Distributes from Ontario farms to chefs who care where ingredients come from.",
        "people": "Paul Sawtell & Grace Mandarano",
        "region": "Ontario",
        "supplies": "Meat, dairy, produce, grains.",
        "logo": "100kmfoods.png",
    },
    {
        "slug": "the-new-farm",
        "name": "The New Farm",
        "blurb": "Certified organic. Family-run. Cycle-driven. The farm that anchors Toronto's best kitchens through every season.",
        "people": "Brent Preston & Gillian Flies",
        "region": "Creemore, ON",
        "supplies": "Salad greens, vegetables, herbs.",
        "logo": "thenewfarm.png",
    },
]

BUILDINGS = [
    {"name": "East Room",         "address": "507 King St E, Toronto",      "type": "Co-working",          "status": "Live"},
    {"name": "The Selby",         "address": "592 Sherbourne St, Toronto",  "type": "Luxury rental",       "status": "Live"},
    {"name": "Club Apex",         "address": "Yonge & Bloor (3rd floor)",    "type": "Members club",        "status": "Live"},
    {"name": "King Charlotte",    "address": "11 Charlotte St, Toronto",     "type": "Condominium",         "status": "Q3 2026"},
    {"name": "The Well",          "address": "486 Front St W, Toronto",      "type": "Mixed-use residence", "status": "Q4 2026"},
    {"name": "One Bloor East",    "address": "1 Bloor St E, Toronto",        "type": "Luxury rental",       "status": "Q4 2026"},
]

NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
    ("Farms",         "/farms.html"),
]

FOOTER_NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
    ("Farms",         "/farms.html"),
    ("Buildings",     "/buildings.html"),
    ("For properties","/for-properties.html"),
    ("For restaurants","/for-restaurants.html"),
    ("FAQ",           "/faq.html"),
]
