"""Canonical BestDish content — restaurants, chefs, dishes, buildings, farms.
Sourced from packaging PDFs, nutrition workbooks, and bestdish.ca."""

RESTAURANTS = {
    "la-palma": {
        "name": "La Palma",
        "address": "849 Dundas St W",
        "city": "Toronto, ON",
        "postal": "M6J 1V5",
        "blurb": "Known for modern Italian cooking — traditional techniques, ingredient quality, precision.",
        "chef": "Craig Harding",
        "logo": "LaPalma.png",
    },
    "lucie": {
        "name": "Lucie",
        "address": "100 Yonge St",
        "city": "Toronto, ON",
        "postal": "M5C 2W1",
        "blurb": "An homage to a grandmother in southwestern France — butter, roasting meat, simmering wine. The belief that feeding people well is one of the greatest acts of love.",
        "chef": "Michael Angeloni",
        "logo": "Lucie.png",
    },
    "pukka": {
        "name": "Pukka",
        "address": "778 St Clair Ave W",
        "city": "York, ON",
        "postal": "M6C 1B6",
        "blurb": "Authentic Indian cooking. Fresh, locally sourced ingredients. Traditional techniques. Bold, balanced flavours.",
        "chef": "Derek Valleau & Dinesh Butola",
        "logo": "Pukka.png",
    },
    "carbon-bar": {
        "name": "The Carbon Bar",
        "address": "99 Queen St E",
        "city": "Toronto, ON",
        "postal": "M5C 1S1",
        "blurb": "An elevated dining venue for Texas-style BBQ, steaks, seafood, and original dishes. Smoke-driven cooking with impeccable hospitality.",
        "chef": "Taylor Well",
        "logo": "CarbonBar.png",
    },
    "carbon-snack-bar": {
        "name": "Carbon Snack Bar",
        "address": "99 Queen St E",
        "city": "Toronto, ON",
        "postal": "M5C 1S1",
        "blurb": "Carbon Bar's sister concept. Smaller plates, sweets, and snacks built on the same smoke-driven approach.",
        "chef": "Taylor Well",
        "logo": "CarbonBar.png",
    },
    "cheese-boutique": {
        "name": "Cheese Boutique",
        "address": "45 Ripley Ave",
        "city": "Toronto, ON",
        "postal": "M6S 1A8",
        "blurb": "One of Canada's most respected specialty food retailers. Under Afrim Pristine's leadership, a destination for quality and expertise in aged cheese.",
        "chef": "Afrim Pristine",
        "logo": "CheeseBoutique.png",
    },
    "queen-and-beaver": {
        "name": "The Queen & Beaver",
        "address": "35 Elm St",
        "city": "Toronto, ON",
        "postal": "M5G 1H1",
        "blurb": "A British-style pub turning out elevated comfort food. Pies, roasts, classics done carefully.",
        "chef": "Duncan Simpson",
        "logo": "QueenBeaver.png",
    },
    "le-gourmand": {
        "name": "Le Gourmand",
        "address": "152 Spadina Ave",
        "city": "Toronto, ON",
        "postal": "M5V 2L1",
        "blurb": "A neighbourhood bakery known across the city for the perfect chocolate chip cookie.",
        "chef": "The Nunes Family",
        "logo": "LeGourmand.png",
    },
    "slowhand": {
        "name": "Slowhand",
        "address": "1300 Queen St E",
        "city": "Toronto, ON",
        "postal": "M4L 1C5",
        "blurb": "Detroit-style pizza done right — caramelised cheese crust, square pan, deep texture.",
        "chef": "Brett Feeley",
        "logo": "Slowhand.png",
    },
    "piano-piano": {
        "name": "Piano Piano",
        "address": "55 Colborne St",
        "city": "Toronto, ON",
        "postal": "M5E 1E3",
        "blurb": "Approachable Italian cooking with a focus on consistency and flavour.",
        "chef": "Victor Barry",
        "logo": "PianoPiano.png",
    },
    "forno-cultura": {
        "name": "Forno Cultura",
        "address": "609 King St W",
        "city": "Toronto, ON",
        "postal": "M5V 1M5",
        "blurb": "An artisanal Italian bakery — sourdough, pastry, biscotti made with patience and respect for tradition.",
        "chef": "Andrea Mastrandrea",
        "logo": "FornoCultura.png",
    },
}

DISHES = [
    {
        "slug": "100-layer-lasagna",
        "name": "100 Layer Lasagna",
        "category": "Savoury",
        "restaurant": "la-palma",
        "tagline": "Handmade. One hundred layers. Built with locally sourced meats and Italian cheeses.",
        "chef_note": "This dish represents the way we build food in the restaurant — with patience, repetition, and attention to detail. Every layer matters.",
        "chef_signature": "Craig Harding",
        "image": "100layer.jpg",
        "weight": "503 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Canned tomatoes, Mozzarella cheese, Flour, Ground meat mix (beef, pork, veal), Whole milk, Pasteurized egg yolks, Grana Padano cheese, Chicken stock, Olive oil, Onions, White wine, Butter, Carrots, Tomato paste, Whole eggs, Celery, Garlic.",
        "contains": "Wheat, Milk, Egg.",
        "may_contain": "Anchovies, Mustard, Sesame, Soybean, Hazelnut and Pecan.",
        "nutrition": {
            "Calories": "570",
            "Fat": "32 g (42% DV)",
            "Saturated": "14 g + Trans 0.5 g (73% DV)",
            "Carbs": "42 g (13% DV)",
            "Fibre": "4 g",
            "Sugars": "7 g (7% DV)",
            "Protein": "30 g",
            "Sodium": "780 mg (33% DV)",
        },
        "heat": {
            "oven":      "Preheat to 375°F. Remove lid and cover with foil. Heat for 30–35 minutes. Remove foil and heat an additional 5 minutes.",
            "microwave": "Remove lid. Heat on high for 5–7 minutes.",
        },
    },
    {
        "slug": "beef-bourguignon",
        "name": "Beef Bourguignon",
        "category": "Savoury",
        "restaurant": "lucie",
        "tagline": "Slow-braised in red wine. The dish that defines the restaurant.",
        "chef_note": "This is the dish my grandmother taught me — patience, butter, wine, time. It's the most honest thing I cook.",
        "chef_signature": "Michael Angeloni",
        "image": "beef-bourguignon-dish.jpg",
        "weight": "450 g",
        "serving": "1.5 cups (340 g)",
        "ingredients": "Beef chuck, Red wine, Beef stock, Mushrooms, Pearl onions, Bacon lardons, Carrots, Tomato paste, Garlic, Butter, Flour, Thyme, Bay leaf, Parsley.",
        "contains": "Wheat, Milk.",
        "may_contain": "Mustard, Sulphites.",
        "nutrition": {
            "Calories": "480",
            "Fat": "26 g (35% DV)",
            "Saturated": "11 g + Trans 0.4 g (58% DV)",
            "Carbs": "18 g (6% DV)",
            "Fibre": "3 g",
            "Sugars": "6 g (6% DV)",
            "Protein": "38 g",
            "Sodium": "690 mg (29% DV)",
        },
        "heat": {
            "oven":      "Preheat to 350°F. Remove lid and cover with foil. Heat for 25–30 minutes.",
            "microwave": "Remove lid. Heat on high for 5–6 minutes. Stir halfway.",
        },
    },
    {
        "slug": "butter-chicken",
        "name": "Butter Chicken Curry",
        "category": "Savoury",
        "restaurant": "pukka",
        "tagline": "Tomato, cream, fenugreek. Roasted chicken, slow-built spice. Built to taste like the dining room.",
        "chef_note": "We don't shortcut the gravy. It cooks down for hours so the spice rounds out — that's what makes it Pukka.",
        "chef_signature": "Derek Valleau & Dinesh Butola",
        "image": "butter-chicken.jpg",
        "weight": "475 g",
        "serving": "1 cup curry + 3/4 cup rice (475 g)",
        "ingredients": "Chicken thigh, Tomatoes, Cream, Butter, Onions, Ginger, Garlic, Fenugreek leaves, Garam masala, Cumin, Coriander, Turmeric, Cardamom, Cinnamon, Chili, Basmati rice, Cilantro, Salt.",
        "contains": "Milk.",
        "may_contain": "Tree nuts, Mustard.",
        "nutrition": {
            "Calories": "620",
            "Fat": "28 g (37% DV)",
            "Saturated": "13 g + Trans 0.4 g (68% DV)",
            "Carbs": "52 g (17% DV)",
            "Fibre": "4 g",
            "Sugars": "8 g (8% DV)",
            "Protein": "34 g",
            "Sodium": "820 mg (35% DV)",
        },
        "heat": {
            "oven":      "Preheat to 375°F. Remove lid and cover with foil. Heat for 20–25 minutes.",
            "microwave": "Remove lid. Heat on high for 4–6 minutes. Stir halfway.",
        },
    },
    {
        "slug": "cheesemaster-mac",
        "name": "Cheesemaster Mac",
        "category": "Savoury",
        "restaurant": "cheese-boutique",
        "tagline": "Aged cheddar, mozzarella, Grana Padano, parmesan crust. Built by Cheese Boutique.",
        "chef_note": "I built this around the cheeses I'd serve a guest at home. The crust is the moment.",
        "chef_signature": "Afrim Pristine",
        "image": "cheesemaster-mac.jpg",
        "weight": "420 g",
        "serving": "1.5 cups (340 g)",
        "ingredients": "Macaroni pasta, Aged cheddar, Mozzarella, Grana Padano, Parmesan, Whole milk, Cream, Butter, Flour, Onion, Garlic, Mustard powder, Nutmeg, Salt, Black pepper.",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Mustard.",
        "nutrition": {
            "Calories": "680",
            "Fat": "34 g (45% DV)",
            "Saturated": "20 g + Trans 0.8 g (100% DV)",
            "Carbs": "58 g (19% DV)",
            "Fibre": "3 g",
            "Sugars": "8 g (8% DV)",
            "Protein": "28 g",
            "Sodium": "720 mg (31% DV)",
        },
        "heat": {
            "oven":      "Preheat to 375°F. Remove lid and cover with foil. Heat for 25–30 minutes. Remove foil and heat an additional 5 minutes for a crisp top.",
            "microwave": "Remove lid. Heat on high for 4–5 minutes. Stir halfway.",
        },
    },
    {
        "slug": "cheeseburger-pot-pie",
        "name": "Cheeseburger Pot Pie",
        "category": "Savoury",
        "restaurant": "queen-and-beaver",
        "tagline": "Burger, rebuilt inside a pastry shell. Structured. Composed. Unmistakably a Queen & Beaver pie.",
        "chef_note": "We took the cheeseburger apart and put it back together as a pie. Same flavours, better structure.",
        "chef_signature": "Duncan Simpson",
        "image": "cheeseburger-pot-pie.jpg",
        "weight": "510 g",
        "serving": "1 pie (300 g)",
        "ingredients": "Ground beef, Cheddar cheese, Onions, Pickles, Tomato, Mustard, Worcestershire, Beef stock, Butter, Flour, Egg wash, Pastry (flour, butter, salt, water).",
        "contains": "Wheat, Milk, Egg, Mustard.",
        "may_contain": "Soy, Sesame.",
        "nutrition": {
            "Calories": "900",
            "Fat": "50 g (67% DV)",
            "Saturated": "17 g + Trans 1 g (90% DV)",
            "Carbs": "62 g (21% DV)",
            "Fibre": "3 g",
            "Sugars": "5 g (5% DV)",
            "Protein": "36 g",
            "Sodium": "1020 mg (44% DV)",
        },
        "heat": {
            "oven":      "Preheat to 375°F. Remove lid. Heat for 20–25 minutes until pastry is golden.",
            "microwave": "Not recommended — pastry loses structure.",
        },
    },
    {
        "slug": "le-grand-fromage",
        "name": "Le Grand Fromage Pizza",
        "category": "Savoury",
        "restaurant": "slowhand",
        "tagline": "Detroit-style. Caramelised cheese crust to the edge. Square pan, deep texture.",
        "chef_note": "The corners are the point. We cheese to the edge so it caramelises against the pan — that crunch is the dish.",
        "chef_signature": "Brett Feeley",
        "image": "le-grand-fromage.jpg",
        "weight": "560 g",
        "serving": "2 cups (300 g)",
        "ingredients": "Dough (flour, water, yeast, salt, olive oil), Mozzarella, Wisconsin brick cheese, Tomato sauce, Parmigiano, Olive oil, Oregano, Garlic, Black pepper.",
        "contains": "Wheat, Milk.",
        "may_contain": "Egg, Soy.",
        "nutrition": {
            "Calories": "800",
            "Fat": "32 g (42% DV)",
            "Saturated": "13 g + Trans 0.5 g (65% DV)",
            "Carbs": "92 g (31% DV)",
            "Fibre": "5 g",
            "Sugars": "6 g (6% DV)",
            "Protein": "32 g",
            "Sodium": "1100 mg (47% DV)",
        },
        "heat": {
            "oven":      "Preheat to 425°F. Remove from box and place on baking tray. Heat for 10–12 minutes.",
            "microwave": "Remove lid. Heat on high for 3–4 minutes. (Oven preferred for crust.)",
        },
    },
    {
        "slug": "pitmaster-platter",
        "name": "Pitmaster Platter",
        "category": "Savoury",
        "restaurant": "carbon-bar",
        "tagline": "Signature smokehouse platter — St. Louis ribs, smoked brisket, cheddar jalapeño sausage, pulled pork.",
        "chef_note": "This is the table at Carbon Bar — everything we smoke, in one box. The brisket is the boss.",
        "chef_signature": "Taylor Well",
        "image": "pitmaster-platter.jpg",
        "weight": "598 g",
        "serving": "2 servings (598 g)",
        "ingredients": "St. Louis pork ribs, Smoked brisket, Cheddar jalapeño sausage (pork, cheddar, jalapeño, spices), Pulled pork, Dry rub (paprika, brown sugar, salt, garlic, black pepper, mustard), BBQ sauce (tomato, vinegar, brown sugar, molasses, spices).",
        "contains": "Milk, Mustard.",
        "may_contain": "Wheat, Soy.",
        "nutrition": {
            "Calories": "1080",
            "Fat": "62 g (83% DV)",
            "Saturated": "22 g + Trans 1 g (115% DV)",
            "Carbs": "28 g (9% DV)",
            "Fibre": "2 g",
            "Sugars": "18 g (18% DV)",
            "Protein": "82 g",
            "Sodium": "1480 mg (63% DV)",
        },
        "heat": {
            "oven":      "Preheat to 350°F. Remove lid and cover with foil. Heat for 25–30 minutes.",
            "microwave": "Remove lid. Heat on high for 6–8 minutes. Rest 2 minutes.",
        },
    },
    {
        "slug": "nutella-tiramisu",
        "name": "Nutella Tiramisu",
        "category": "Sweet",
        "restaurant": "piano-piano",
        "tagline": "Layered mascarpone and Nutella cream with espresso. Rich. Composed. Balanced.",
        "chef_note": "This is a playful version of a classic, built to be rich but balanced.",
        "chef_signature": "Victor Barry",
        "image": "nutella-tiramisu-dish.jpg",
        "weight": "240 g",
        "serving": "1 portion (120 g)",
        "ingredients": "Mascarpone, Cream, Sugar, Nutella (hazelnuts, sugar, palm oil, cocoa, milk, lecithin, vanillin), Egg yolks, Ladyfingers (flour, sugar, eggs), Espresso, Marsala wine, Cocoa powder.",
        "contains": "Milk, Egg, Wheat, Hazelnut, Soy.",
        "may_contain": "Tree nuts.",
        "nutrition": {
            "Calories": "440",
            "Fat": "28 g (37% DV)",
            "Saturated": "16 g + Trans 0.5 g (82% DV)",
            "Carbs": "38 g (13% DV)",
            "Fibre": "2 g",
            "Sugars": "28 g (28% DV)",
            "Protein": "7 g",
            "Sodium": "85 mg (4% DV)",
        },
        "heat": {
            "oven":      "Do not heat — dessert.",
            "microwave": "Do not heat — dessert. Thaw in refrigerator overnight before serving.",
        },
    },
    {
        "slug": "butter-tarts",
        "name": "Butter Tarts",
        "category": "Sweet",
        "restaurant": "carbon-snack-bar",
        "tagline": "A traditional Canadian dessert with a sweet filling and flaky crust.",
        "chef_note": "I worked through twenty versions of this filling. The maple is the answer.",
        "chef_signature": "Taylor Well",
        "image": "butter-tarts.webp",
        "weight": "165 g",
        "serving": "1 tart (55 g)",
        "ingredients": "Sugars (brown sugar, corn syrup, maple syrup), Butter, Flour, Liquid eggs, Water, Apple cider vinegar, Salt, Vanilla extract.",
        "contains": "Wheat, Milk, Egg.",
        "may_contain": "Tree nuts, Soy.",
        "nutrition": {
            "Calories": "220",
            "Fat": "11 g (15% DV)",
            "Saturated": "5 g + Trans 0.2 g (26% DV)",
            "Carbs": "27 g (9% DV)",
            "Fibre": "0 g",
            "Sugars": "15 g (15% DV)",
            "Protein": "2 g",
            "Sodium": "180 mg (8% DV)",
        },
        "heat": {
            "oven":      "Preheat to 325°F. Remove from container. Heat for 8–10 minutes for warm-from-the-oven feel.",
            "microwave": "Remove from container. Heat on high for 20–30 seconds. (Oven preferred.)",
        },
    },
    {
        "slug": "chocolate-chip-cookies",
        "name": "Chocolate Chip Cookies",
        "category": "Sweet",
        "restaurant": "le-gourmand",
        "tagline": "A raw cookie designed to be baked fresh — soft centre, crisp edges.",
        "chef_note": "Bake them from frozen. The contrast between the centre and the edge only happens when the dough is cold going in.",
        "chef_signature": "The Nunes Family",
        "image": "chocolate-chip-cookies-dish.jpg",
        "weight": "330 g (6 cookies)",
        "serving": "1 cookie (55 g)",
        "ingredients": "Flour, Butter, Sugars (brown sugar, white sugar), Chocolate chips (sugar, chocolate, cocoa butter, milk ingredients, soy lecithin, natural flavour), Eggs, Vanilla, Salt, Baking soda.",
        "contains": "Wheat, Milk, Egg, Soy.",
        "may_contain": "Tree nuts, Peanut.",
        "nutrition": {
            "Calories": "220",
            "Fat": "11 g (15% DV)",
            "Saturated": "5 g + Trans 0.2 g (26% DV)",
            "Carbs": "27 g (9% DV)",
            "Fibre": "0 g",
            "Sugars": "15 g (15% DV)",
            "Protein": "2 g",
            "Sodium": "180 mg (8% DV)",
        },
        "heat": {
            "oven":      "Preheat to 350°F. Place cookies on parchment-lined tray, 2 inches apart. Bake from frozen for 14–16 minutes until edges are golden.",
            "microwave": "Not recommended — defeats the purpose. Bake.",
        },
    },
]

FARMS = [
    {
        "slug": "100km-foods",
        "name": "100km Foods",
        "blurb": "Founded in 2008 by Paul Sawtell and Grace Mandarano. Distributes from Ontario farms to chefs who care where ingredients come from.",
        "people": "Paul Sawtell & Grace Mandarano",
        "region": "Ontario",
        "supplies": "Meat, dairy, produce, grains.",
        "logo": "100kmfoods.png",
    },
    {
        "slug": "the-new-farm",
        "name": "The New Farm",
        "blurb": "Certified organic. Family-run. Cycle-driven. The farm that anchors Toronto's best kitchens through every season.",
        "people": "Brent Preston & Gillian Flies",
        "region": "Creemore, ON",
        "supplies": "Salad greens, vegetables, herbs.",
        "logo": "thenewfarm.png",
    },
]

BUILDINGS = [
    {"name": "East Room",         "address": "507 King St E, Toronto",      "type": "Co-working",          "status": "Live"},
    {"name": "The Selby",         "address": "592 Sherbourne St, Toronto",  "type": "Luxury rental",       "status": "Live"},
    {"name": "Club Apex",         "address": "Yonge & Bloor (3rd floor)",    "type": "Members club",        "status": "Live"},
    {"name": "King Charlotte",    "address": "11 Charlotte St, Toronto",     "type": "Condominium",         "status": "Q3 2026"},
    {"name": "The Well",          "address": "486 Front St W, Toronto",      "type": "Mixed-use residence", "status": "Q4 2026"},
    {"name": "One Bloor East",    "address": "1 Bloor St E, Toronto",        "type": "Luxury rental",       "status": "Q4 2026"},
]

NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
    ("Farms",         "/farms.html"),
]

FOOTER_NAV = [
    ("Browse meals",  "/meals.html"),
    ("How it works",  "/how-it-works.html"),
    ("Chefs",         "/chefs.html"),
    ("Farms",         "/farms.html"),
    ("Buildings",     "/buildings.html"),
    ("For properties","/for-properties.html"),
    ("For restaurants","/for-restaurants.html"),
    ("FAQ",           "/faq.html"),
]
